# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "accounts", :force => true do |t|
    t.string   "title"
    t.text     "description"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "parent_id"
    t.string   "vat_type"
    t.integer  "vat_percent",    :limit => 10, :precision => 10, :scale => 0
    t.string   "account_number"
    t.integer  "fiscal_year_id"
  end

  add_index "accounts", ["fiscal_year_id"], :name => "accounts_fiscal_year_id_fk"
  add_index "accounts", ["parent_id", "account_number"], :name => "index_accounts_on_parent_id_and_account_number"

  create_table "event_lines", :force => true do |t|
    t.integer "event_id"
    t.integer "account_id"
    t.integer "amount",     :limit => 10, :precision => 10, :scale => 0
  end

  add_index "event_lines", ["event_id"], :name => "event_lines_event_id_fk"
  add_index "event_lines", ["account_id"], :name => "event_lines_account_id_fk"

  create_table "events", :force => true do |t|
    t.integer  "fiscal_year_id"
    t.integer  "receipt_number"
    t.date     "event_date"
    t.text     "description"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "events", ["fiscal_year_id"], :name => "events_fiscal_year_id_fk"
  add_index "events", ["event_date"], :name => "index_events_on_event_date"
  add_index "events", ["receipt_number"], :name => "index_events_on_receipt_number"

  create_table "fiscal_years", :force => true do |t|
    t.text     "description"
    t.date     "start_date"
    t.date     "end_date"
    t.integer  "company_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "fiscal_years", ["start_date"], :name => "index_fiscal_years_on_start_date"

  create_table "sessions", :force => true do |t|
    t.string   "session_id"
    t.text     "data"
    t.datetime "updated_at"
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

end
